### ISSUE TITLE
Add Project based guides

### ISSUE THREAD

**Issue by Qodestackr** [superfaceai/docs#106]
I would like to build various projects as guides(tutorials). I feel like it will be great if they can certainly be displayed either within the blog or under the docs for technical users.

Kindly guide me where needed.

**Comment by martyndavies** [comment]
Hey @Qodestackr, thanks but we are not currently accepting external guides at this time. If we change this in future we will announce it on GitHub Discussions.

**Comment by Qodestackr** [comment]
Kein Problem! 💯
