### ISSUE TITLE
Connect Algolia DocSearch

### ISSUE THREAD

**Issue by kysely** [superfaceai/docs#3]
This waits for the site to be deployed on its final URL + Algolia [requires the site](https://docsearch.algolia.com/docs/who-can-apply/#the-checklist) to already have some final content on it.

- https://docusaurus.io/docs/search#connecting-algolia
- https://docsearch.algolia.com/apply/

**Comment by jnv** [comment]
@kysely Any updates yet?

**Comment by kysely** [comment]
Oops, forgot to update this. We got declined for free hosting version. 

Will have to run our own crawler.

**Comment by jnv** [comment]
Any rationale why we were rejected? Would it make sense to reapply?

**Comment by jnv** [comment]
But yeah, looks like we could run the crawler in GitHub Action, there are also other alternatives: https://docusaurus.io/docs/search

**Comment by kysely** [comment]
> We're really sorry to have to turn down your request, but we are receiving so many applications everyday that we now have to give priority to OS projects. We hope you understand. 

Basically they don't see us as OSS.

I replied to that decision with a description of how open source we are. Got an answer from Algolia to reapply. So I did, but with the same result.

**Comment by kysely** [comment]
> But yeah, looks like we could run the crawler in GitHub Action, there are also other alternatives: https://docusaurus.io/docs/search

Yes, that should be easy to set up and I think they still provide 10k queries for free

**Comment by jnv** [comment]
I think this issue can be closed?

**Comment by kysely** [comment]
Yes
