### ISSUE TITLE
Use docs-specific logo

### ISSUE THREAD

**Issue by jnv** [superfaceai/docs#50]
As suggested by @kysely, we could use a logo similar to one we have for blog:

![](https://user-images.githubusercontent.com/616767/135297393-7ef2be18-e8d8-4a1b-ae88-0bd1a2689a6c.png)

However, the logo may change as there is different proposal for new landing pages, so I am posting this here as a reminder for myself.

**Comment by martyndavies** [comment]
Closing. Not something we'll address at this time. Thanks.
