### ISSUE TITLE
Rewrite "How to create a capability" section

### ISSUE THREAD

**Issue by jnv** [superfaceai/docs#75]
- Consistent naming and titles
- Get rid of "capability" and other terms – depends on #74 
- Keep linear readability in mind
- Consider covering #58

Open questions:
- Should we design it as Tutorial or Guides
  - Perhaps a tutorial covering all steps with particular integration in mind would be the best start

**Comment by tmladek** [comment]
- refer to up-to-date testing best practices, i.e. using https://github.com/superfaceai/testing

**Comment by martyndavies** [comment]
Closing as relates to the older version of Superface. Thanks all.
