### ISSUE TITLE
OneSDK reference: Document new methods from v1.4.0+

### ISSUE THREAD

**Issue by jnv** [superfaceai/docs#90]
- [ ] `configuredProviders` https://github.com/superfaceai/one-sdk-js/issues/211
- [ ] super.json simple retry policy https://github.com/superfaceai/one-sdk-js/issues/210
- [ ] Passing super.json into client constructor ([1.5.0](https://github.com/superfaceai/one-sdk-js/releases/tag/v1.5.0)
- [ ] Passing security values into perform ([1.5.0](https://github.com/superfaceai/one-sdk-js/releases/tag/v1.5.0)

**Comment by martyndavies** [comment]
Closing as relates to old Superface. Thanks @jnv!
