### ISSUE TITLE
Upgrade guide improvements

### ISSUE THREAD

**Issue by jnv** [superfaceai/docs#97]
Just my scratchpad to collect possible improvements.

----

Removed from the release announcement – I think the mechanics and differences like this should be explained somewhere:

While OneSDK v1 relied on local profile files (`.supr`, installed into `superface/grid`), OneSDK v2 will fetch and cache compiled profiles in the runtime. If the `super.json` configuration file is not found, the `getProfile` method must specify the profile version (e.g., `weather/forecast-city@1.0.0`) and `perform` must specify the provider (`{ provider: 'wttr-in' }`).

If you already use OneSDK with `super.json` file, you don’t need to change anything. The `super.json` file acts as a central place for locking profile versions and decoupling providers configuration from the code. It is also needed for using local profiles and maps (see [below more details]).

---

**Comment by martyndavies** [comment]
Closing. Relates to the older version of Superface. Thanks @jnv!
